.PHONY: dev
dev:
	@$(MAKE) dev -C egads
	@$(MAKE) dev -C egadslite

.PHONY: test
test:
	@$(MAKE) test -C egads
	@$(MAKE) test -C egadslite

.PHONY: cleanall
cleanall:
	@$(MAKE) cleanall -C egads
	@$(MAKE) cleanall -C egadslite
	@$(MAKE) cleanall -C egadscommon
	