#	Makefile for ESP/XDDM and Cart3D AIM
#
ifndef ESP_ROOT
$(error ESP_ROOT must be set -- Please fix the environment...)
endif
#
IDIR  = $(ESP_ROOT)/include
include $(IDIR)/$(ESP_ARCH)
LDIR  = $(ESP_ROOT)/lib
BDIR  = $(ESP_ROOT)/bin
ifdef ESP_BLOC
ODIR  = $(ESP_BLOC)/obj
TDIR  = $(ESP_BLOC)/test
else
ODIR  = .
TDIR  = $(ESP_ROOT)/bin
endif
ifndef CART3DLIB
CART3DLIB = $(IDIR)
endif
XMLIB = $(shell xml2-config --libs)
# do to MAC problem on Xcode 8 & OSX 10.11
ifeq ($(ESP_ARCH),DARWIN64)
XMLIB = -lxml2
endif


ifeq ("$(XMLIB)","")
default:
	@echo "XML developer libarary missing. Not compiling cart3dAIM."
else
default:	$(LDIR)/cart3dAIM.so $(TDIR)/cart3dTest $(BDIR)/ESPxddm
endif


$(BDIR)/ESPxddm:	$(ODIR)/ESPxddm.o $(ODIR)/writeTrix.o $(ODIR)/xddm.o \
			$(ODIR)/bodyTess.o
	$(CC) -o $(BDIR)/ESPxddm $(ODIR)/ESPxddm.o $(ODIR)/writeTrix.o \
		$(ODIR)/xddm.o $(ODIR)/bodyTess.o -L$(LDIR) -locsm -legads \
		-L$(CART3DLIB)/$(CART_ARCH) -lc3dio -lCart3D \
		-lpthread -ldl $(FRPATH) $(XMLIB) -lm

$(LDIR)/cart3dAIM.so:	$(ODIR)/cart3dAIM.o $(ODIR)/writeTrix.o \
			$(ODIR)/bodyTess.o $(LDIR)/libaimUtil.a $(LDIR)/libutils.a
	$(CC) $(SOFLGS) -o $(LDIR)/cart3dAIM.so $(ODIR)/cart3dAIM.o \
		$(ODIR)/writeTrix.o $(ODIR)/bodyTess.o -L$(LDIR) -laimUtil \
		-locsm -legads -ludunits2 -lutils -L$(CART3DLIB)/$(CART_ARCH) \
		-lc3dio -lCart3D $(XMLIB) -lm

$(ODIR)/cart3dAIM.o:	cart3dAIM.c $(IDIR)/capsTypes.h
	$(CC) -c $(COPTS) $(DEFINE) -I$(IDIR) -I../utils -I$(CART3DLIB)/xddm \
		cart3dAIM.c -o $(ODIR)/cart3dAIM.o

$(ODIR)/ESPxddm.o:	ESPxddm.c 
	$(CC) -c $(COPTS) $(DEFINE) -I$(IDIR) -I$(CART3DLIB)/xddm \
		-I. `xml2-config --cflags` ESPxddm.c -o $(ODIR)/ESPxddm.o

$(ODIR)/writeTrix.o:	writeTrix.c 
	$(CC) -c $(COPTS) $(DEFINE) -I$(IDIR) -I$(CART3DLIB)/c3dio \
		-I$(CART3DLIB)/libCart3D -I$(CART3DLIB)/xddm \
		writeTrix.c -o $(ODIR)/writeTrix.o

$(ODIR)/xddm.o:	$(CART3DLIB)/xddm/xddm.c 
	$(CC) -c $(COPTS) $(DEFINE) -w -I$(CART3DLIB)/xddm -I. \
		`xml2-config --cflags` $(CART3DLIB)/xddm/xddm.c \
		 -o $(ODIR)/xddm.o

$(ODIR)/bodyTess.o:	bodyTess.c 
	$(CC) -c $(COPTS) $(DEFINE) -I$(IDIR) bodyTess.c -o $(ODIR)/bodyTess.o

$(TDIR)/cart3dTest:	$(ODIR)/cart3dTest.o $(LDIR)/$(CSHLIB)
	$(CC) -o $(TDIR)/cart3dTest $(ODIR)/cart3dTest.o \
		-L$(LDIR) -lcaps -locsm -legads $(RPATH) -lm -ldl

$(ODIR)/cart3dTest.o:	cart3dTest.c $(IDIR)/caps.h
	$(CC) -c $(COPTS) $(DEFINE) -I$(IDIR) cart3dTest.c \
		-o $(ODIR)/cart3dTest.o

clean:
	-rm -f $(ODIR)/writeTrix.o $(ODIR)/xddm.o $(ODIR)/bodyTess.o \
		$(ODIR)/ESPxddm.o $(ODIR)/cart3dAIM.o $(ODIR)/cart3dTest.o

cleanall:	clean
	-rm -f $(BDIR)/ESPxddm $(LDIR)/cart3dAIM.so $(TDIR)/cart3dTest
	
dox:
	(cd doc; doxygen cart3dAIM_dox.cfg; cd latex; make; mv refman.pdf CART3DAIM.pdf)

doxclean:
	(cd doc; rm -f INPUT; rm -rf html latex; rm -f cart3dAIM.tag)	
